#!/usr/bin/env bash
# Mock PI Agent for Orchestration Test
# Simulates:
# - Session ID generation (for resume testing)
# - File writing (for HTML/CSS/JS)
# - Token usage logging (for cost testing)
# - Resume logic (skips context if --resume passed)

# Fake token usage
INPUT_TOKENS=500
OUTPUT_TOKENS=200

# Parse args
RESUMING=false
SESSION_ID=""

for arg in "$@"; do
  if [[ "$arg" == "--resume" ]]; then
    RESUMING=true
  elif [[ "$arg" =~ ^[a-f0-9-]{36}$ ]]; then
    SESSION_ID="$arg"
  fi
done

# If not resuming, generate a session ID
if [[ "$RESUMING" == "false" ]]; then
  echo "Session ID: $(uuidgen 2>/dev/null || echo "550e8400-e29b-41d4-a716-446655440000")"
else
  echo "Resuming Session: $SESSION_ID"
fi

# Simulate work based on prompt content
# Looking for "Write file: <filename>" in the prompt (passed as last arg usually, or stdin)
PROMPT="${@: -1}"

echo "RECEIVED PROMPT: $PROMPT"

if [[ "$PROMPT" =~ Write\ file:\ ([^[:space:]]+) ]]; then
  FILE="${BASH_REMATCH[1]}"
  echo "Writing to $FILE..."
  mkdir -p "$(dirname "$FILE")"
  echo "// Content for $FILE generated by PI" > "$FILE"
fi

# Simulate cost tracking log (usually done by wrapper, but here we just echo for debug)
echo "TOKEN_USAGE: $INPUT_TOKENS $OUTPUT_TOKENS"
